<a href="https://colab.research.google.com/github/nichakornchaisuwan/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np #package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

##Nimpy Array (matrix) จาก list

สร้าง numpy array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np_a.shape

(2, 3)

In [8]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

matrix transpose

In [9]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [11]:
np_z = np.zeros((4,5)) # identity การบวก
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np_o = np.ones((5,6)) #identity การคูณ
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random

In [16]:
np.random.randn(5,5) #random เลขมาจาก normal distribution ที่มี mu=0 std = 1

array([[ 0.82983701,  0.43920803,  1.53735393, -1.5124899 , -0.4515988 ],
       [-0.65432553,  0.91274766, -0.64478724,  0.92726684,  1.18397344],
       [-0.81324149,  1.0139447 ,  0.81288786,  0.21760096,  0.43533036],
       [ 1.89434537, -0.3376314 ,  0.93510073,  0.37688192,  2.16485244],
       [ 0.0962738 ,  0.10634039, -1.1130899 , -0.59043572,  0.69403303]])

In [17]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu=2 std = 5

array([[-3.4315401 ,  7.91108941, -0.56768228],
       [ 7.69514662, -7.17174504, -2.12439228],
       [-7.4468145 ,  7.86637907, -5.03633989]])

In [19]:
np.random.randint(5,11,(4,5))   #เลขจำนวนเต็ม ระหว่าง 5-10 จึงต้องใช้ 5,11 ขนาด 4*5

array([[ 6,  7, 10,  8, 10],
       [ 7, 10,  8,  8,  6],
       [10,  8,  6,  8,  9],
       [ 8,  7,  6,  9,  6]])