<a href="https://colab.research.google.com/github/nichakornchaisuwan/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

##Nimpy Array (matrix) จาก list

สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [7]:
np_z = np.zeros((4,5)) # identity การบวก
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6)) #identity การคูณ
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random

In [10]:
np.random.randn(5,5) #random เลขมาจาก normal distribution ที่มี mu=0 std = 1

array([[-1.53279837,  0.32785805,  0.69933844,  0.09665862, -0.62090145],
       [ 0.54916013,  1.4318746 , -0.17599415, -0.02047154,  0.19240708],
       [-0.60952557, -1.76367566, -0.87799748,  0.2029416 , -0.24643667],
       [-1.45702569, -0.14843087,  0.1639914 ,  1.02436626,  1.05965205],
       [-0.44783584, -0.02829319,  0.96410088,  0.02105018, -0.49564219]])

In [11]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu=2 std = 5

array([[ 1.09512071, -3.08038834,  6.24645248],
       [-0.55887805, -1.19371178,  4.43680509],
       [ 6.5488218 ,  2.15540256,  4.92547715]])

In [12]:
np.random.randint(5,11,(4,5))   #เลขจำนวนเต็ม ระหว่าง 5-10 จึงต้องใช้ 5,11 ขนาด 4*5

array([[ 8,  9,  7,  8, 10],
       [ 7,  5,  5,  7,  7],
       [10,  9,  7,  6,  7],
       [10,  7,  5,  7,  5]])

matrix transpose

In [13]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np_a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
1+ np_a # บวก matrix ด้วย scalar  มีขนาด ไม่มีทิศทาง

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
2*np_a #multipling scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [18]:
np_a+np_c #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [20]:
np_a.shape

(2, 3)

In [25]:
np_c.shape

(2, 3)

In [27]:
np_c.T.shape

(3, 2)

In [24]:
np.dot(np_a,np_c.T) #multipling matrix to matrix (a,b)*(b,c) = (a,c)

array([[28, 10],
       [73, 28]])

##Indexing &Silcing

ชี้ตัวที่เป็นค่าใน matrix อย่างไร

In [28]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np_a[1,1]

5

In [30]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
np_a[0,:]

array([1, 2, 3])

###Useful function


In [33]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.sum(np_a)

21

In [34]:
np.sum(np_a,axis=0) # เอาด้านแถวมารวมกัน

array([5, 7, 9])

In [35]:
np.sum(np_a,axis=1) # เอาด้านหลักมารวมกัน

array([ 6, 15])

In [36]:
np.mean(np_a)

3.5

In [37]:
np.mean(np_a,axis = 0 )  # หาค่า mean ของ column

array([2.5, 3.5, 4.5])

### วนลูปเอง

####summation

```np.sum(np_a)```

In [38]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a [row,col]
        print(f'we are at row = {row},col = {col} np_a[{row},{col}] = {np_a[row,col]} sum_all = {sum_all}')

we are at row = 0,col = 0 np_a[0,0] = 1 sum_all = 1
we are at row = 0,col = 1 np_a[0,1] = 2 sum_all = 3
we are at row = 0,col = 2 np_a[0,2] = 3 sum_all = 6
we are at row = 1,col = 0 np_a[1,0] = 4 sum_all = 10
we are at row = 1,col = 1 np_a[1,1] = 5 sum_all = 15
we are at row = 1,col = 2 np_a[1,2] = 6 sum_all = 21


```np.sum(np_a,axis = 0)```

In [42]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a [row,col]
print(sum_all)

[5. 7. 9.]


####Quiz กลุ่ม
วนลูปหาค่า
* ```np.sum(np_a,axis = 1```
* ```np.mean(np_a)```
* ```np.mean(np_a,axis = 0```
* ```np.mean(np_a,axis = 1```

In [51]:
# np.max(np_a,axis=1)
max_all = np.zeros(np_a.shape[0])

for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        max_all[row] = max(np_a[row])
print(max_all)

[3. 6.]
